// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (user_id, action, status, request_ip, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, status, request_ip, created_at, metadata
`

type InsertAuditLogParams struct {
	UserID    *int64  `json:"user_id"`
	Action    string  `json:"action"`
	Status    string  `json:"status"`
	RequestIp *string `json:"request_ip"`
	Metadata  []byte  `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Status,
		arg.RequestIp,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Status,
		&i.RequestIp,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listAuditLogsCursor = `-- name: ListAuditLogsCursor :many
SELECT id, user_id, action, status, request_ip, created_at, metadata
FROM audit_logs
WHERE
    ($1::timestamptz IS NULL OR created_at < $1 OR (created_at = $1 AND id < $2))
    AND ($3::bigint IS NULL OR user_id = $3)
    AND ($4::text IS NULL OR action = $4)
    AND ($5::text IS NULL OR status = $5)
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListAuditLogsCursorParams struct {
	CursorTs     pgtype.Timestamptz `json:"cursor_ts"`
	CursorID     *int64             `json:"cursor_id"`
	FilterUserID *int64             `json:"filter_user_id"`
	FilterAction *string            `json:"filter_action"`
	FilterStatus *string            `json:"filter_status"`
	LimitCount   int32              `json:"limit_count"`
}

func (q *Queries) ListAuditLogsCursor(ctx context.Context, arg ListAuditLogsCursorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsCursor,
		arg.CursorTs,
		arg.CursorID,
		arg.FilterUserID,
		arg.FilterAction,
		arg.FilterStatus,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Status,
			&i.RequestIp,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
