// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AssignDefaultRole(ctx context.Context, userID int64) error
	AssignRoleByName(ctx context.Context, arg AssignRoleByNameParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolesByUserID(ctx context.Context, userID int64) ([]string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
