// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_roles.sql

package sqlcgen

import (
	"context"
)

const assignDefaultRole = `-- name: AssignDefaultRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id FROM roles WHERE name = 'user'
ON CONFLICT DO NOTHING
`

func (q *Queries) AssignDefaultRole(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, assignDefaultRole, userID)
	return err
}

const assignRoleByName = `-- name: AssignRoleByName :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id FROM roles WHERE name = $2
ON CONFLICT DO NOTHING
`

type AssignRoleByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) AssignRoleByName(ctx context.Context, arg AssignRoleByNameParams) error {
	_, err := q.db.Exec(ctx, assignRoleByName, arg.UserID, arg.Name)
	return err
}

const getRolesByUserID = `-- name: GetRolesByUserID :many
SELECT r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetRolesByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
